In [110]:
import numpy as np

In [111]:
data = np.loadtxt(open("./data/iris.csv", "rb"), delimiter=",", usecols=(0,1,2,3))
labels = np.loadtxt(open("./data/iris.csv", "rb"), delimiter=",", dtype=np.string_, usecols=(4))

In [112]:
print(data[:10])
print(data.shape)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]
(150, 4)


In [113]:
print(labels[:10])
print(len(labels))

[b'Iris-setosa' b'Iris-setosa' b'Iris-setosa' b'Iris-setosa'
 b'Iris-setosa' b'Iris-setosa' b'Iris-setosa' b'Iris-setosa'
 b'Iris-setosa' b'Iris-setosa']
150


In [114]:
m = data.shape[0]
indices = np.arange(m)
np.random.shuffle(indices)

#Normalize the data (cols)
data = data / data.max(axis=0)

#Split data into random training and test sets
training_indices, test_indices = indices[:(2*m)//3], indices[2*m//3:]
training_set, test_set = data[training_indices], data[test_indices]
training_labels, test_labels = labels[training_indices], labels[test_indices]

In [115]:
#calculate the euclidean distance of example with respect to all rows in data
def distance(example, data):
    return np.sqrt(np.sum((data-example)**2, axis=1))

In [116]:
from scipy import stats
def KNN_predict(K, data, labels, example):
    #calculate distances
    distances = distance(example, data)
    #sort the array and get corresponding indexes
    sorted_indexes = distances.argsort()
    #return the most common label among K points with lowest distance with example
    return stats.mode(labels[sorted_indexes[:K]])[0][0]#.decode('UTF-8')

In [117]:
K = 3
n = test_set.shape[0]
num_correct = 0
for i in range(n):
    example = test_set[i]
    pred = KNN_predict(K, training_set, training_labels,example)
    print("prediction:", pred, "ground truth:",test_labels[i])
    if pred == test_labels[i]:
        num_correct += 1 
print("Accuracy:", num_correct/n)

prediction: b'Iris-versicolor' ground truth: b'Iris-versicolor'
prediction: b'Iris-virginica' ground truth: b'Iris-virginica'
prediction: b'Iris-virginica' ground truth: b'Iris-virginica'
prediction: b'Iris-virginica' ground truth: b'Iris-virginica'
prediction: b'Iris-versicolor' ground truth: b'Iris-versicolor'
prediction: b'Iris-versicolor' ground truth: b'Iris-versicolor'
prediction: b'Iris-virginica' ground truth: b'Iris-virginica'
prediction: b'Iris-setosa' ground truth: b'Iris-setosa'
prediction: b'Iris-setosa' ground truth: b'Iris-setosa'
prediction: b'Iris-setosa' ground truth: b'Iris-setosa'
prediction: b'Iris-setosa' ground truth: b'Iris-setosa'
prediction: b'Iris-setosa' ground truth: b'Iris-setosa'
prediction: b'Iris-versicolor' ground truth: b'Iris-versicolor'
prediction: b'Iris-versicolor' ground truth: b'Iris-versicolor'
prediction: b'Iris-setosa' ground truth: b'Iris-setosa'
prediction: b'Iris-versicolor' ground truth: b'Iris-versicolor'
prediction: b'Iris-setosa' groun